common: &common
  adapter:  postgresql
  encoding: unicode
  username: postgres # OR your username
  #password: YOUR PASSWORD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *common
  database: portfolio_dev # OR your database name

test:
  <<: *common
  database: portfolio_test # OR your database name
  min_messages: WARNING

staging:
  <<: *common
  database: portfolio_staging # OR your database name

production:
  adapter:  postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['USER'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>